# Generated by Django 3.2 on 2024-01-11 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecipeIngredientAmount',
            new_name='RecipeIngredient',
        ),
    ]
